Indexes::search() improvements
meilisearch/meilisearch-php pull request #120
Opened 2020-11-24 17:40 UTC by Guikingone

Hi everyone 👋 

As mentioned here: https://github.com/meilisearch/meilisearch-php/issues/119, here's the `SearchResult` class and the improvements that comes with it. 

There's just a small "DX" way that I'm not sure about: 

- When using `SearchResult::filter()` should the `hits` array be reset to 0 or stay as it? 

Thanks for the feedback and have a great day 🙂

2020-12-10 15:27 UTC, curquiza commented
Hello @Guikingone! So sorry for the delay!!!
The integration team is mostly ok with this change! 😄
I just need a final discussion with the developer relation manager before reviewing and merging this PR: indeed, we would apply this change in other SDKs (ruby, python...), that's why I want to be sure before taking this kind of decision that differs from Algolia!
Thanks again for your patience and your suggestion -> that's exactly the kind of solution I was looking for to help users managing their search results!

2020-12-16 07:47 UTC, Guikingone commented
Hello @curquiza 👋 

The checks are green after a small refactoring, feel free to review it when you have time, I've introduced the `json()` method as discussed 🙂

2020-12-16 10:00 UTC, curquiza commented
Thank you so much @Guikingone!
I review it asap! 👍

2020-12-17 09:58 UTC, ppshobi approved these changes
Seems good to me. Real nice touch with the tests

2020-12-18 17:00 UTC, curquiza requested changes
Thanks for this huge job, I just ask for small modifications!

About your question, yes let it as it is for the moment, it seems ok for me 🙂

Again, thank you so much for your work 🙏 Be sure we are going to extend this way of handling search result to our other SDKs.

FYI: I'm not going to release right after merging this PR. I indeed need to discuss naming with my team, and most of all, another breaking PR is planned so I will do the push to Packagist after all the breaking changes are done 😇

2020-12-21 17:55 UTC, Guikingone commented on src/Search/SearchResult.php
> +    public function json(): string
Fixed

2020-12-21 17:56 UTC, Guikingone commented on src/Search/SearchResult.php
> +            'nbHits' => \count($this->hits),
Fixed

2020-12-21 17:56 UTC, Guikingone commented on src/Endpoints/Indexes.php
> +            $searchResult = $searchResult->filter($options['filteringHits']);
Improved 🙂

2020-12-21 20:46 UTC, curquiza approved these changes
Finally merging! Thanks a lot @Guikingone and also @ppshobi! 🎉 

bors merge

2020-12-21 20:48 UTC, merged