Updating code-sample for v0.27.0
meilisearch/meilisearch-php pull request #320
Opened 2022-04-27 16:35 UTC by alallema

2022-04-27 17:27 UTC, brunoocasali requested changes
Good job! 🥇 🎉 

I found some small items I think they could be addressed before the merge :)

2022-04-27 17:27 UTC, brunoocasali commented on .code-samples.meilisearch.yaml
> +    'enabled' => False
```suggestion
    'enabled' => false
```

2022-04-28 12:14 UTC, bidoubiwa requested changes

2022-04-28 12:14 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +        'disableOnAttributes' => ['title']
I think indentation should be 2 spaces

2022-04-28 13:25 UTC, bidoubiwa approved these changes
LGTM 🔥

2022-04-28 13:31 UTC, merged