Add separator tokens setting
meilisearch/meilisearch-php pull request #572
Opened 2023-08-22 14:40 UTC by alallema

# Pull Request

## Related issue
Fixes #570 

## What does this PR do?
- Add separator tokens settings
- Create tests

2023-08-22 17:34 UTC, norkunas commented on tests/Settings/NonSeparatorTokensTest.php
> +        $this->assertEquals($newNonSeparatorTokens, $nonSeparatorTokens);
`assertSame` should be used

2023-08-28 21:10 UTC, brunoocasali requested changes

2023-08-28 21:10 UTC, brunoocasali commented on tests/Settings/SeparatorTokensTest.php
> +        $this->assertIsValidPromise($promise);
```suggestion
```

2023-09-05 20:42 UTC, brunoocasali approved these changes
LGTM!! Thanks @alallema

2023-09-05 20:46 UTC, merged