Add `proximityPrecision` management methods
meilisearch/meilisearch-php pull request #606
Opened 2024-01-10 18:26 UTC by brunoocasali

Pre-release work for v1.6.

2024-01-10 18:39 UTC, norkunas requested changes

2024-01-10 18:39 UTC, norkunas commented on tests/Settings/ProximityPrecisionTest.php
> +        $this->assertEquals($default, "byWord");
```suggestion
        $this->assertSame('byWord', $default);
```

2024-01-10 18:39 UTC, norkunas commented on tests/Settings/ProximityPrecisionTest.php
> +        $this->assertEquals("byAttribute", $this->index->getProximityPrecision());
```suggestion
        $this->assertSame('byAttribute', $this->index->getProximityPrecision());
```

2024-01-10 18:39 UTC, norkunas commented on tests/Settings/ProximityPrecisionTest.php
> +        $this->assertEquals($this->index->getProximityPrecision(), "byWord");
```suggestion
        $this->assertEquals('byWord', $this->index->getProximityPrecision());
```

2024-01-10 18:40 UTC, norkunas requested changes

2024-01-10 18:40 UTC, norkunas commented on .code-samples.meilisearch.yaml
> +  $client->index('books')->updateProximityPrecision("byAttribute");
```suggestion
  $client->index('books')->updateProximityPrecision('byAttribute');
```

2024-01-10 19:06 UTC, norkunas approved these changes

2024-01-11 12:07 UTC, curquiza requested changes
Thanks Bruno

Can you fix PHP stan CI?

2024-01-15 01:08 UTC, merged

2024-01-15 04:31 UTC, norkunas commented on src/Endpoints/Delegates/HandlesSettings.php
> -     */
why removed this one?

2024-01-15 04:34 UTC, norkunas commented on src/Endpoints/Delegates/HandlesSettings.php
> -     */
also I wonder is it an enum or can be anything?