Implements the update documents by function
meilisearch/meilisearch-php pull request #664
Opened 2024-07-31 15:27 UTC by irevoire

# Pull Request

## Related issue
Fixes https://github.com/meilisearch/meilisearch-php/issues/661

## What does this PR do?
- Implements the update documents by function method
- Add a test

2024-07-31 15:33 UTC, norkunas commented on src/Endpoints/Delegates/HandlesDocuments.php
> +     * @param non-empty-string @function
```suggestion
     * @param non-empty-string $function
```

2024-07-31 15:33 UTC, norkunas commented on src/Endpoints/Delegates/HandlesDocuments.php
> +     * @param array{filter: non-empty-string|list<non-empty-string>, context: array}|null @options
```suggestion
     * @param array{filter: non-empty-string|list<non-empty-string>, context: array<non-empty-string, mixed>}|null $options
```

2024-07-31 15:42 UTC, norkunas approved these changes

2024-08-01 03:45 UTC, norkunas commented on src/Endpoints/Delegates/HandlesDocuments.php
> +        return $this->http->post(self::PATH.'/'.$this->uid.'/documents/edit', ['function' => $function, ...$options]);
```suggestion
     * @param array{filter: non-empty-string|list<non-empty-string>|null, context: array<non-empty-string, mixed>} $options
     */
    public function updateDocumentsByFunction(string $function, array $options = [])
    {
        return $this->http->post(self::PATH.'/'.$this->uid.'/documents/edit', ['function' => $function, ...$options]);
```
spread operator, cannot work with non array

2024-08-01 08:21 UTC, norkunas commented on src/Endpoints/Delegates/HandlesDocuments.php
> +     * @param array{filter: non-empty-string|list<non-empty-string>|null, context: array<non-empty-string, mixed>} $options
```suggestion
     * @param array{filter?: non-empty-string|list<non-empty-string>|null, context?: array<non-empty-string, mixed>} $options
```
If filter or context is not mandatory

2024-08-01 09:16 UTC, curquiza commented
@irevoire I cannot merge despite the approval of @norkunas because the tests are failing 😊

2024-08-01 09:16 UTC, curquiza submitted a review, later dismissed
@irevoire can you update the tests? 😇

2024-08-01 09:17 UTC, curquiza requested changes
Request of change for the tests (no miss click this time 🤞 )

2024-08-01 11:32 UTC, curquiza approved these changes

2024-08-01 11:32 UTC, merged